// Mirrors backend/src/constants/permissions.js. Used only to decide what to
// render - never to decide what is allowed.
export const CAPABILITIES = {
  SELF_PASSWORD_CHANGE: 'SELF_PASSWORD_CHANGE',
  POLICY_VIEW_ASSIGNED: 'POLICY_VIEW_ASSIGNED',
  POLICY_ACKNOWLEDGE: 'POLICY_ACKNOWLEDGE',
  COMPLIANCE_VIEW_SELF: 'COMPLIANCE_VIEW_SELF',
  TRAINING_COMPLETE: 'TRAINING_COMPLETE',
  INCIDENT_SUBMIT: 'INCIDENT_SUBMIT',
  INCIDENT_VIEW_OWN: 'INCIDENT_VIEW_OWN',
  COMPLIANCE_VIEW_DEPARTMENT: 'COMPLIANCE_VIEW_DEPARTMENT',
  REMINDER_SEND: 'REMINDER_SEND',
  REPORT_EXPORT: 'REPORT_EXPORT',
  SIMULATION_VIEW_RESULTS: 'SIMULATION_VIEW_RESULTS',
  COMPLIANCE_VIEW_ORGANISATION: 'COMPLIANCE_VIEW_ORGANISATION',
  POLICY_AUTHOR: 'POLICY_AUTHOR',
  TRAINING_AUTHOR: 'TRAINING_AUTHOR',
  INCIDENT_TRIAGE: 'INCIDENT_TRIAGE',
  USER_MANAGE: 'USER_MANAGE',
  AUDIT_VIEW: 'AUDIT_VIEW',
  SIMULATION_MANAGE: 'SIMULATION_MANAGE',
};

export const ROLES = { EMPLOYEE: 'EMPLOYEE', MANAGER: 'MANAGER', ADMIN: 'ADMIN' };

export const DEPARTMENT_LABELS = {
  SALES: 'Sales',
  WAREHOUSE: 'Warehouse',
  ADMINISTRATION: 'Administration',
  MANAGEMENT: 'Management',
};

export const ROLE_LABELS = {
  EMPLOYEE: 'Employee',
  MANAGER: 'Manager',
  ADMIN: 'Administrator',
};

// UC-02 step 8: each role lands somewhere different after signing in.
export const HOME_PATH_BY_ROLE = {
  [ROLES.EMPLOYEE]: '/my-tasks',
  [ROLES.MANAGER]: '/department',
  [ROLES.ADMIN]: '/admin',
};

export const homePathFor = (user) => HOME_PATH_BY_ROLE[user?.role] || '/my-tasks';
