// Machine-readable error codes returned in the `error.code` field of the
// standard envelope (spec section 8.9). The client branches on these; the
// human-readable `message` is for display only and may be reworded freely.

const AppErrorCode = Object.freeze({
  // Authentication
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  PASSWORD_REUSED: 'PASSWORD_REUSED',
  STEP_UP_REQUIRED: 'STEP_UP_REQUIRED',

  // Authorisation
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  SCOPE_VIOLATION: 'SCOPE_VIOLATION',

  // Compliance
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  USER_OUT_OF_SCOPE: 'USER_OUT_OF_SCOPE',
  NO_REMINDER_RECIPIENTS: 'NO_REMINDER_RECIPIENTS',
  REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',

  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = AppErrorCode;
