// Actions recorded in the append-only `auditLogs` collection (spec section 7.14).
// Only the M1 (authentication and RBAC) set is defined here; later modules add
// their own entries as they land.

const AUDIT_ACTIONS = Object.freeze({
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGIN_INACTIVE: 'AUTH_LOGIN_INACTIVE',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_TOKEN_REFRESHED: 'AUTH_TOKEN_REFRESHED',
  AUTH_TOKEN_REUSE_DETECTED: 'AUTH_TOKEN_REUSE_DETECTED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_STEP_UP_SUCCESS: 'AUTH_STEP_UP_SUCCESS',
  AUTH_STEP_UP_FAILURE: 'AUTH_STEP_UP_FAILURE',
  RBAC_DENIED: 'RBAC_DENIED',
  RBAC_SCOPE_VIOLATION: 'RBAC_SCOPE_VIOLATION',
  COMPLIANCE_DASHBOARD_VIEWED: 'COMPLIANCE_DASHBOARD_VIEWED',
  COMPLIANCE_REPORT_EXPORTED: 'COMPLIANCE_REPORT_EXPORTED',
  COMPLIANCE_REMINDER_SENT: 'COMPLIANCE_REMINDER_SENT',
  COMPLIANCE_OVERDUE_SWEEP: 'COMPLIANCE_OVERDUE_SWEEP',
});

const AUDIT_OUTCOME = Object.freeze({
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  DENIED: 'DENIED',
});

const AUDIT_ENTITY_TYPE = Object.freeze({
  USER: 'USER',
  SESSION: 'SESSION',
  POLICY: 'POLICY',
  POLICY_VERSION: 'POLICY_VERSION',
  TRAINING_MODULE: 'TRAINING_MODULE',
  INCIDENT: 'INCIDENT',
  CAMPAIGN: 'CAMPAIGN',
  ASSIGNMENT: 'ASSIGNMENT',
  COMPLIANCE_REPORT: 'COMPLIANCE_REPORT',
});

module.exports = { AUDIT_ACTIONS, AUDIT_OUTCOME, AUDIT_ENTITY_TYPE };
