const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');

const formatDate = (value) => (value ? new Date(value).toISOString().slice(0, 10) : '');

const metadataRows = ({ generatedBy, scope, generatedAt, filters }) => [
  ['Compliance Report'],
  ['Generated by', generatedBy.fullName],
  ['Generated at', generatedAt.toISOString()],
  ['Scope', scope.department || 'Organisation'],
  ['Filters', JSON.stringify(filters || {})],
  [],
];

const generateXlsx = async ({ rows, generatedBy, scope, filters, generatedAt = new Date() }) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Savikro Compliance Platform';
  workbook.created = generatedAt;
  const sheet = workbook.addWorksheet('Compliance');
  metadataRows({ generatedBy, scope, filters, generatedAt }).forEach((row) => sheet.addRow(row));
  const header = sheet.addRow([
    'Employee ID', 'Employee', 'Email', 'Department', 'Role', 'Item Type', 'Item',
    'Status', 'Assigned', 'Due', 'Completed', 'Reminders', 'Last reminded',
  ]);
  header.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1D4ED8' } };
  rows.forEach(({ assignment, user }) => sheet.addRow([
    user.employeeId, user.fullName, user.email, assignment.department, assignment.userRole,
    assignment.itemType, assignment.itemTitle, assignment.status, formatDate(assignment.assignedAt),
    formatDate(assignment.dueDate), formatDate(assignment.completedAt), assignment.remindersSent,
    formatDate(assignment.lastRemindedAt),
  ]));
  sheet.columns.forEach((column) => { column.width = Math.min(38, Math.max(12, column.values.reduce((max, value) => Math.max(max, String(value || '').length), 0) + 2)); });
  sheet.autoFilter = { from: 'A7', to: 'M7' };
  return workbook.xlsx.writeBuffer();
};

const generatePdf = ({ rows, generatedBy, scope, filters, generatedAt = new Date() }) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 42, size: 'A4' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).text('Savikro Compliance Report');
    doc.moveDown(0.5).fontSize(9).fillColor('#475569');
    doc.text(`Generated by: ${generatedBy.fullName}`);
    doc.text(`Generated at: ${generatedAt.toISOString()}`);
    doc.text(`Scope: ${scope.department || 'Organisation'}`);
    if (Object.keys(filters || {}).length) doc.text(`Filters: ${JSON.stringify(filters)}`);
    doc.moveDown().fillColor('#111827').fontSize(10).text(`Assignments: ${rows.length}`, { underline: true });
    doc.moveDown(0.5);
    rows.forEach(({ assignment, user }, index) => {
      if (doc.y > 740) doc.addPage();
      doc.fontSize(8).font('Helvetica-Bold').text(`${index + 1}. ${user.employeeId} - ${user.fullName}`);
      doc.font('Helvetica').text(
        `${assignment.itemType}: ${assignment.itemTitle} | ${assignment.status} | Due ${formatDate(assignment.dueDate)}`
      );
      doc.moveDown(0.35);
    });
    doc.end();
  });

module.exports = { generateXlsx, generatePdf };
